### ISSUE TITLE
Firebase Setup

### ISSUE THREAD

**Issue by rithvikreddybasani** [Dan2418/VocaVisionary#5]
can you tell me how to setup firebase for this?

**Comment by Dan2418** [comment]
First you have to create a Firebase account , you can create using gmail account in the firebase website 
Then  go to firebase  console and create a project .
Ensure you have enabled the following things:
1. Authentication
2. Firestore
3. Realtime Database
4.  Storage
These are important for this project and also ensure to activate in **test mode** / enable the read - write operation 
For authentication enable email/password option
Then go to project settings "general" part there would be enable web app with "</>" icon enable it. After you would get the firebase configuration key like this
```
const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: ""
};
```
paste those in the mentioned files and the project would be able to run successfully.

**Comment by rithvikreddybasani** [comment]
I am unable to get the users who have booked an appointment in dashboard
section. Can you please tell what is the issue?

**Comment by Dan2418** [comment]
Could you give more details if you can provide a screenshot exactly where the problem is ?

**Comment by rithvikreddybasani** [comment]
![image](https://github.com/user-attachments/assets/42160acb-cd24-45d3-8951-8c207169195e)

**Comment by Dan2418** [comment]
Did you book any appointment in the appointment page?
Initially there would be no appointments, you have to book an appointment in the appointment page inorder for this to work. Before that you have to add counsellors from the dashboard page only after that you can get list of counsellors in appointment section.
Also ensure that you have enabled Firebase in that web page and the check the reference name in which the data being accessed is same as the reference name provided in your Firebase console.

**Comment by Dan2418** [comment]
I hope your issue has been resolved.

**Comment by rithvikreddybasani** [comment]
Yes
